language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install --upgrade pip setuptools coverage coveralls nose
script:
    - printenv PWD
    - pip install .
    - nosetests --with-doctest --with-coverage --cover-package=wos
after_success:
    coveralls
